### ISSUE TITLE
EAN_13

### ISSUE THREAD

**Issue by leving1** [yyyyu/react-native-barcode#7]
Hello,

i want to implement a Barcode scanner (EAN13) my Code looks currently like this: 

import React, { Component } from "react";
import { View, Button, Alert, StyleSheet } from "react-native";
import * as RNLBarCode from "@yyyyu/react-native-barcode";

const Scanner = RNLBarCode.Scanner;

class Barcode extends  React.Component {
  state = {
    visible: true,
    scanEnable: true,
    scannerSize: 300,
    decoder: RNLBarCode.Decoder.Auto,
    // RNLBarCode.Type.[Common].[BarCodeType]
    formats: RNLBarCode.Type.Common.EAN_13,
    torch: RNLBarCode.TorchMode.Off
  };

  render() {
    return (
      <View style={styles.container}>
        {this.state.visible && (
          <Scanner
            enable={this.state.scanEnable}
            decoder={this.state.decoder}
            formats={this.state.formats}
            torch={this.state.torch}
            onResult={this.handleResult}
            style={{
              width: this.state.scannerSize,
              height: this.state.scannerSize
            }}
          />
        )}
        <Button onPress={this.toggleVisible} title={"Toggle Visible"} />
        <Button onPress={this.toggleScanEnable} title={"Toggle ScanEnable"} />
        <Button onPress={this.toggleTorch} title={"Toggle Torch"} />
      </View>
    );
  }

  handleResult = (result, error) => {
    this.setState({ scanEnable: false });
    if (error) {
      Alert.alert(RNLBarCode.Errors[error.code], error.message, [
        { text: "Ok" }
      ]);
    } else {
      Alert.alert(
        "Success!",
        `format: ${RNLBarCode.Type.Common[result.format]}, content: ${
          result.content
        }`,
        [{ text: "Ok", onPress: () => this.setState({ scanEnable: true }) }]
      );
    }
  };

  toggleVisible = () => {
    this.setState({ visible: !this.state.visible });
  };

  toggleScanEnable = () => {
    this.setState({ scanEnable: !this.state.scanEnable });
  };

  toggleTorch = () => {
    this.setState({
      torch:
        this.state.torch === RNLBarCode.TorchMode.Off
          ? RNLBarCode.TorchMode.On
          : RNLBarCode.TorchMode.Off
    });
  };
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff"
  }
});

Where can i put my EAN_13 values, what changes need to be done ? 

Thanks for your help :)

**Comment by yyyyu** [comment]
zbar sometimes give wrong result, if you use android os, switch zxing decoder or select all formats try again. hope to help you.

```jsx
// put the format here
<Scanner
  ...others
  formats={RNLBarCode.Type.Common.EAN_13}
/>

// if still can't recognized, you can ignore formats prop, default select all probable formats
<Scanner
  ...others
/>
```

**Comment by leving1** [comment]
Thanks for your help! Can you provide the complete documentation ? 
I have some EAN13 Codes, where can i put them into the Code ? 

Thank you so much for the support.

**Comment by yyyyu** [comment]
Do you want to detect images contain EAN13 code? maybe you should use [decode method](https://github.com/yyyyu/react-native-barcode/blob/master/example/Decoder.js#L17).

```javascript
RNLBarCode.decode({
  data: [Your image e.g. require('./path/ean13_img.png')],
  formats: RNLBarCode.Type.Common.EAN_13,
  decoder: RNLBarCode.Decoder.Auto
})
.then((result) => console.log(result))
.catch((err) => console.errror(err))
```
